### PR TITLE
feat/add_wasm_light_client

### PR DESCRIPTION
**Pull request by tungle-notional**
Closes: #122 

This pull request implements the WASM light client

### CODE REVIEW

**Comment by faddat** [comment]
Looking good.  Remember that you can always reference the IBC simapp, and that you should always give a description and link to the issue, if there is one.

**Comment by faddat** [comment]
@tungle-notional - when I did the merge, I also corrected version numbers.  We want eve to use ibc v8.1.0 and the latest released version of the wasm client.

**Comment by tungle-notional** [comment]
@faddat Yeah, sure. But do you know this bug? It happens after I rebase from the main branch and change the version to make it compatible
Screenshot 2024-03-12 at 17 55 56

**Comment by faddat** [comment]
the bug you posted is from the version of wasmvm being used.  If we use the same wasmvm as ibc that will be fine.  Also, it might be needed to update wasmvm in ibc-go

**Pull request closed without merging**
