### PR TITLE
deps: bump alliance and fix proto annotation

### LINKED ISSUE #194: Not have proto annotation
service feeabstraction.feeabs.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
File at mytestnet/config/genesis.json is a valid genesis file
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
service feeabstraction.feeabs.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
service feeabstraction.feeabs.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation

### PR DESCRIPTION
**Pull request by minhngoc274**
Fix #194 

## Summary by CodeRabbit

- **Refactor**
	- Improved internal parameter management for enhanced system performance and reliability.

### CODE REVIEW

**Comment by minhngoc274** [comment]
I use my latest update base on terra-classic/alliance/release/v0.4.x https://github.com/notional-labs/alliance/commit/9fb96066d68eb0263334ba92efa8436007cd7cdd

**Comment by faddat** [comment]
Nice, have you made a PR to the tfl repo also?

**Comment by hoank101** [comment]
why not use the original repo? https://github.com/terra-money/alliance/releases/tag/v0.4.3

**Comment by minhngoc274** [comment]
PR created here https://github.com/terra-money/alliance/pull/360. I will change once it have been merge

**Review by hoank101 — APPROVED** [review]
LGTM

**Comment by hoank101** [comment]
thank you for PR

**Pull request merged**
